# Generated by Django 4.2.13 on 2024-06-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_product',
            name='Avatar_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='url_image'),
        ),
    ]
